---
Organizations:

    - &OrdererOrg
        Name: OrdererOrg
        ID: OrdererMSP
        MSPDir: crypto-config/ordererOrganizations/vin.gov/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('OrdererMSP.admin')"

    - &DMV
        Name: DMVMSP
        ID: DMVMSP
        MSPDir: crypto-config/peerOrganizations/dmv.vin.gov/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('DMVMSP.admin', 'DMVMSP.peer', 'DMVMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('DMVMSP.admin', 'DMVMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('DMVMSP.admin')"
        AnchorPeers:
            - Host: peer0.dmv.vin.gov
              Port: 7051

    - &Manufacturers
        Name: ManufacturersMSP
        ID: ManufacturersMSP
        MSPDir: crypto-config/peerOrganizations/manufacturers.vin.gov/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('ManufacturersMSP.admin', 'ManufacturersMSP.peer', 'ManufacturersMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('ManufacturersMSP.admin', 'ManufacturersMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('ManufacturersMSP.admin')"
        AnchorPeers:
            - Host: peer0.manufacturers.vin.gov
              Port: 7051

    - &Civilians
        Name: CiviliansMSP
        ID: CiviliansMSP
        MSPDir: crypto-config/peerOrganizations/civilians.vin.gov/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('CiviliansMSP.admin', 'CiviliansMSP.peer', 'CiviliansMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('CiviliansMSP.admin', 'CiviliansMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('CiviliansMSP.admin')"
        AnchorPeers:
            - Host: peer0.civilians.vin.gov
              Port: 7051

Capabilities:
    Channel: &ChannelCapabilities
        V1_3: true
    Orderer: &OrdererCapabilities
        V1_1: true
    Application: &ApplicationCapabilities
        V1_3: true
        V1_2: false
        V1_1: false

Application: &ApplicationDefaults
    Organizations:
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"

Orderer: &OrdererDefaults
    OrdererType: solo
    Addresses:
        - orderer.vin.gov:7050
    BatchTimeout: 2s
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB

    Kafka:
        Brokers:
            - 127.0.0.1:9092
    Organizations:
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"

Channel: &ChannelDefaults
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
    Capabilities:
        <<: *ChannelCapabilities

Profiles:

    OrdererGenesis:
        <<: *ChannelDefaults
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *OrdererOrg
            Capabilities:
                <<: *OrdererCapabilities
        Consortiums:
            VinConsortium:
                Organizations:
                    - *DMV
                    - *Manufacturers
                    - *Civilians
    VinNetworkChannel:
        Consortium: VinConsortium
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *DMV
                - *Manufacturers
                - *Civilians
            Capabilities:
                <<: *ApplicationCapabilities
