OrdererOrgs:
  - Name: Orderer
    Domain: vin.gov
    Specs:
      - Hostname: orderer
PeerOrgs:
  - Name: DMV
    Domain: dmv.vin.gov
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1
  - Name: Manufacturers
    Domain: manufacturers.vin.gov
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1
  - Name: Civilians
    Domain: civilians.vin.gov
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1
