version: '2'

volumes:
  orderer.vin.gov:
  peer0.dmv.vin.gov:
  peer1.dmv.vin.gov:
  peer0.manufacturers.vin.gov:
  peer1.manufacturers.vin.gov:

networks:
  vin_main_network:

services:

  orderer.vin.gov:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.vin.gov
    container_name: orderer.vin.gov
    networks:
      - vin_main_network

  peer0.dmv.vin.gov:
    container_name: peer0.dmv.vin.gov
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.dmv.vin.gov
    networks:
      - vin_main_network

  peer1.dmv.vin.gov:
    container_name: peer1.dmv.vin.gov
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.dmv.vin.gov
    networks:
      - vin_main_network

  peer0.manufacturers.vin.gov:
    container_name: peer0.manufacturers.vin.gov
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.manufacturers.vin.gov
    networks:
      - vin_main_network

  peer1.manufacturers.vin.gov:
    container_name: peer1.manufacturers.vin.gov
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.manufacturers.vin.gov
    networks:
      - vin_main_network

  peer0.civilians.vin.gov:
    container_name: peer0.civilians.vin.gov
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.civilians.vin.gov
    networks:
      - vin_main_network

  peer1.civilians.vin.gov:
    container_name: peer1.civilians.vin.gov
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.civilians.vin.gov
    networks:
      - vin_main_network

  ca.dmv.vin.gov:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.dmv.vin.gov
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.dmv.vin.gov-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/ca.dmv.vin.gov-key.pem
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw'
    volumes: 
      - ./crypto-config/peerOrganizations/dmv.vin.gov/ca:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.dmv.vin.gov
    networks:
      - vin_main_network

  ca.manufacturers.vin.gov:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.manufacturers.vin.gov
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.manufacturers.vin.gov-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/ca.manufacturers.vin.gov-key.pem
    ports:
      - "7055:7055"
    command: sh -c 'fabric-ca-server start -b admin:adminpw'
    volumes: 
      - ./crypto-config/peerOrganizations/manufacturers.vin.gov/ca:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.manufacturers.vin.gov
    networks:
      - vin_main_network

  ca.civilians.vin.gov:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.civilians.vin.gov
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.civilians.vin.gov-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/ca.civilians.vin.gov-key.pem
    ports:
      - "7056:7056"
    command: sh -c 'fabric-ca-server start -b admin:adminpw'
    volumes: 
      - ./crypto-config/peerOrganizations/civilians.vin.gov/ca:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.civilians.vin.gov
    networks:
      - vin_main_network

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.dmv.vin.gov:7051
      - CORE_PEER_LOCALMSPID=DMVMSP
      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/dmv.vin.gov/peers/peer0.dmv.vin.gov/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/dmv.vin.gov/peers/peer0.dmv.vin.gov/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/dmv.vin.gov/peers/peer0.dmv.vin.gov/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/dmv.vin.gov/users/Admin@dmv.vin.gov/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../../chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
        - orderer.vin.gov
        - peer0.dmv.vin.gov
        - peer1.dmv.vin.gov
        - peer0.manufacturers.vin.gov
        - peer1.manufacturers.vin.gov
        - peer0.civilians.vin.gov
        - peer1.civilians.vin.gov

    networks:
      - vin_main_network
